### ISSUE TITLE
Settings scrollbar

### ISSUE THREAD

**Issue by ddennetiere** [PyMoDAQ/pymodaq_plugins_template#11]
Dear PymoDAQ community,
I have recently jumped from 3.5.6 to 4.2.2, I have a preset that articulates a lot of homemade plugins and they have A LOT of parameters. In the old 3.5.6, the parameter display had a vertical (and a horizontal) scrollbar but it seems to have disappeared in 4.2.2.
The trouble is that displaying the parameter now disrupts the whole preset UI with plugins moving out of screen and that disruption is not reversable (hiding settings leaves the dock sizes changed although partly visible).

Is it possible to bring the scrollbars back ?

Cheers,
David

**Comment by seb5g** [comment]
could you be more specific? 
parameters in: DAQ_Move? DAQ_Viewer? PresetManager? All of them?

**Comment by seb5g** [comment]
ok I got it, 

I worked on it in the PR https://github.com/PyMoDAQ/PyMoDAQ/pull/342 together with some features about diplayed values in the UI (and units)
