### ISSUE TITLE
Dual absolute move in DAQ_Move

### ISSUE THREAD

**Issue by ddennetiere** [PyMoDAQ/pymodaq_plugins_template#12]
Dear PyMoDAQ community,
with pymodaq 4, a new feature has appeared: the two absolute move settings (green and red) on top of the DAQ_Move widget.
I do love the feature as one often has to go back and forth between two position.
There is one issue though: the value entered in the fields in only registered as one leaves the item. If one was to say enter "100" then click on the associated arrow, the actuator would move to the position entered before the 100. This unexpected behaviour is a security risk for instruments where collision is possible.

Could the value be cached as one change the position and not as one leaves the lineEdit ? I think it is just a matter of using lineedit textChanged signal instead of editingFinished, but i can be wrong.

Thanks, 
David

**Comment by seb5g** [comment]
solved by #https://github.com/PyMoDAQ/PyMoDAQ/pull/345
