### ISSUE TITLE
Template requires not yet published pymodaq version

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_plugins_template#14]
The template requires the not yet published pymodaq version 4.3. Is this intentional? Is it required for the setup?

https://github.com/PyMoDAQ/pymodaq_plugins_template/blob/c756e672f4cbaae84b5b2a6cbdc32277189dbea8/plugin_info.toml#L16

I'm updating my basler plugin with the new setup method (which is a lot smaller) but do not want to publish a package with unmet requirements.

What is the recommended way to update a plugin package to the newest state?

**Comment by seb5g** [comment]
it is not required for the setup but for some functionality (ease of use really) I introduced a few days ago in the dev branch. These additions are used for the slave/master thing in the control modules template but not mandatory and within the custom_app and extension templates. You should be fine by using it. Did you publish the basler plugin yet?

**Comment by BenediktBurger** [comment]
I already published it quite sime time ago.
Now I wanted to update the part which does not depend on the instrument itself (setup etc.)
The instrument did not change, therefore a new release is not necessary.

**Comment by seb5g** [comment]
ok
