### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_plugins_template#7]
The pre-installed tests fails in my [repo](https://github.com/BenediktBurger/pymodaq_plugins_basler), as they do not find `pymodaq` ([full test job](https://github.com/BenediktBurger/pymodaq_plugins_basler/actions/runs/7652213932/job/20851531060)):

~~~
Obtaining file:///home/runner/work/pymodaq_plugins_basler/pymodaq_plugins_basler
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/runner/work/pymodaq_plugins_basler/pymodaq_plugins_basler/setup.py", line 1, in <module>
          from pymodaq.resources.setup_plugin import setup
      ModuleNotFoundError: No module named 'pymodaq'
      [end of output]
~~~

Where do I have to specify that it requires `pymodaq` in such a way, that the test setup will install it (and all other dependencies)?

I added it to the normal `plugins.toml`, but the test environment does not seem to look at it.

**Comment by seb5g** [comment]
we have to swap two line in the github action yml file, for pymodaq to be installed before the tested package


```
          pip install -e . 
          pip install pymodaq
```

![image](https://github.com/PyMoDAQ/pymodaq_plugins_template/assets/6609955/4fa05a81-b24c-4184-b358-df887afde207)

**Comment by BenediktBurger** [comment]
Thanks for your fast response.
