### ISSUE TITLE
Most recent version of template requires not yet published pymodaq

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_plugins_template#8]
This line:
https://github.com/PyMoDAQ/pymodaq_plugins_template/blob/d1769557ab065a86361282405d56e6aac7658ab6/setup.py#L1

requires a version of pymodaq, which is not yet published.
Therefore, all plugins, which use this line cannot be installed, unless the user has also the most recent (github version) of pymodaq.

I suggest to include it in a try except clause:
~~~python
try:
    import ...
except ModuleNotFoundError:
   # define it manually
~~~

EDIT:
I've noticed, that the default pymodaq version required is 4.1, so both fit together.

**Comment by seb5g** [comment]
Yes I published the required version yesterday so it should be fine. Should we close this?
